# Generated by Django 4.1.7 on 2023-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
